name: Atualizar Ranking PUBG

on:
  schedule:
    - cron: '*/8 * * * *'  # Roda no intervalo mínimo permitido (8 min)
  workflow_dispatch:       # Mantém o botão de rodar manualmente ativo
  push:                    # Roda automaticamente sempre que você salvar um código
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug estrutura
        run: |
          pwd
          ls -la
          
      - name: Executar atualização
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PUBG_API_KEY: ${{ secrets.PUBG_API_KEY }}
        run: python pubg_import.py
        
