      - name: Debug estrutura
        run: |
          pwd
          ls -la

      - name: Executar atualização
        run: python pubg_import.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PUBG_API_KEY: ${{ secrets.PUBG_API_KEY }}
